### ISSUE TITLE
Ability to add rows when using the csv editor

### ISSUE THREAD

**Issue by drewbo** [prose/prose#1002]
I think the only way to add csv rows currently would be to toggle back to the older editor mode

cc: @timwis

**Comment by timwis** [comment]
You should be able to right-click on a row and select "Insert row below/above" - does that not work for you?

**Comment by drewbo** [comment]
Amazing. I'm so glad I cc'ed you

**Comment by timwis** [comment]
Yeah... I think handsontable has an option that keeps an empty row at the bottom, which would be a more obvious experience. I think I disabled that because it was injecting an empty line in the diff, but maybe I'm remembering wrong. Here's a question though: would you have thought to right-click if you wanted to add a column?

**Comment by drewbo** [comment]
Definitely don't want to mess with the diff. Hard to say on the last question, in general I assume web tools aren't responsive to that behavior (same with things like double clicks though which do appear on some tools). I think it's fine to leave right now, I might do some impromptu user testing to see if others have the same issue and maybe we could add some helper text/buttons/etc.
