### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by justinsane** [prose/prose#1093]
Hi - new Prose user here. Terrific work.

Is it possible to re-size images with Prose or Markdown?

I'm uploading original photos to the post that I took on my iPhone. Is it necessary to resize prior to uploading photos on the post?

Thanks.

**Comment by dereklieu** [comment]
Hey @justinsane, there is no faculty for resizing your images in Prose. You could try using css to set the sizes that your images are displayed at. Markdown also [supports inline html](https://stackoverflow.com/questions/40335929/including-html-in-markdown) which you could use to set `width` and `height` attributes. Otherwise, you would need to use a desktop, mobile, or web app to resize images from your phone.

**Comment by justinsane** [comment]
The top code works .

The bottom code doesn't. 

I'm confused.
```
![Monteverde Suspension]({{site.baseurl}}/img/Monteverde_Suspension.jpeg)

<img src="img/Monteverde_Suspension.jpeg" width="400" />
```

**Comment by justinsane** [comment]
I forgot a / before the img/Monteverde_Suspension.jpeg ... 

We're good. Thanks
