### ISSUE TITLE
Don't always include published: false for markdown

### ISSUE THREAD

**Issue by dhcole** [prose/prose#111]
For example, editing a readme.md file in a jekyll site does not need a published: false if it is in the _config.yml to be excluded. This might be tricky to avoid though.

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Create a test case -- a list of steps we can perform to reproduce the problem

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by jgillich** [comment]
So now it always sets `published: true`..is this intended? I don't use Jekyll and have no use for it at all. Can we either not set it by default or hide it behind a config?

**Comment by dereklieu** [comment]
This just happened to me too, on a project that doesn't require it. I agree it's annoying, and doesn't make sense if the file is not in a _posts folder.

**Comment by fghhfg** [comment]
In jekyll, 

`prose.io` create `published: false` if you are in `_posts`.
`prose.io` will note create `published: false` if you are not in `_posts`.

so if you want to create a post inside `_posts`, you need to:
create the post -> back previous page -> reload page -> go into the post -> click `unpublished` icon

... WTF :(

**Comment by fghhfg** [comment]
ok, I got it.

add this in `_config.yml`:
```yaml
prose:
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
```

Everything works perfect!

check here: https://github.com/prose/prose/wiki/Prose-Configuration

**Comment by patcon** [comment]
Yay for prose! Still love this tool.

Just to chime in with another example of things going awry:

This PR created from prose:
https://github.com/highfidelity/hifi-docs-grav-content/pull/191/files

Actions that resulted in PR wew viewing the edit interface and then viewing metadata (not making any explicit changed), and then hitting save.

This is not a jekyll website, and so there is no `_config.yml` and no `_posts/` dir.

Slightly confusing for contributors, and perhaps an irrational for maintainers, but not a blocker :)

Thanks for everything! might come back to submit PR myself later

**Comment by sarajw** [comment]
Hi, I'm slightly confused by all the discussion on this - I don't use Jekyll or a directory called _posts, yet an unneeded `published: false` is always added into any files I create using Prose. It would be nice to avoid this :)

**Comment by babbitt** [comment]
Finally had a moment to get around to this. A bit of a tricky one since as mentioned above there were some red herrings in finding where `published: true` was even being set in the first place. 

I would appreciate some feedback on the PR (#1151) if anyone has a second to read it over but the TL;DR is that I've settled on a pattern that hopefully resolves this issue for everyone not using Jekyll while still retaining the original functionality. From now on `published: true` will no longer appear in front-matter unless explicitly set.

If I don't hear anything in the PR or this issue I'll merge and close both sometime later this week.
