### ISSUE TITLE
use with gitea selfhosted

### ISSUE THREAD

**Issue by Ddataa** [prose/prose#1117]
Hi there,

Thanks for your wonderful work on that amazing project :+1: 

Do you know how it will be possible to self-host a prose instance to use on your own gitea server ?

**Comment by babbitt** [comment]
I've worked on updating the instructions on how to run prose locally. There shouldn't be any issues doing so. That being said it's worth noting that the integration between github and prose is pretty tight. There'd be some non-trivial work on porting over all the functionality and matching API requests. If you're interested in doing the work I'm more than happy to see if it's something we can merge in but since prose is a "Content Editor for Github" according to it's description I'm going to say this isn't something I would consider as a core feature.

Feel free to reopen or comment if needed.
