### ISSUE TITLE
Skip deploy when upload image

### ISSUE THREAD

**Issue by sh-cho** [prose/prose#1120]
![image](https://user-images.githubusercontent.com/11611397/137908334-949c88b0-b97e-49d3-8c6c-26715f0f5e80.png)

Uploading image causes deploying, which is unnecessary.

What about add `[skip ci]` in commit message?

**Comment by dannystaple** [comment]
Configuration to shape the commit messages might be quite a useful general feature.

**Comment by babbitt** [comment]
@sh-cho The PR above should be exactly what you're looking for. It's worth noting that from my testing the [no ci] flag only skips workflow actions, it may not prevent gh-pages from building if you're using the basic build from branch option. If you can give the PR a thumbs up hopefully the maintainers will see and merge.

In the meantime, I'm currently hosting my own fork with some bugfixes and features I've worked on (including this one) @ joebabbitt.com/prosa. Since I want to avoid standing up my own gatekeeper instance and keep everything client-side, I've enabled login via github PAR token. (You'll need to create a token with the repo and user scopes to login).

@dannystaple Re shaping commit messages it certainly isn't off the table functionality wise but probably doesn't make sense for the image upload case. The other wrench in changing commit messages is the fact that message defaults are translated. For now most change messages can be edited before saving in the editor but if there's a specific use case you're looking for let me know and I can take a look.

**Comment by dannystaple** [comment]
Hello, it was specifically about using square brackets to hint to the CI. 

Specifically to the image use case, another way might be to use a changed files action, and skip if only image files are added.

**Comment by babbitt** [comment]
@dannystaple The fix that was just merged should provide the functionality you're asking for unless I'm having a communication mixup. Closing this issue for now; feel free to re-open if you're looking for something else
