### ISSUE TITLE
Folders with spaces in their name appear empty if navigated into

### ISSUE THREAD

**Issue by Tc-001** [prose/prose#1121]
# To reproduce

1. Open https://prose.io/#Tc-001/Prose-bug-repro/tree/main
2. Navigate to `./Folder_no_spaces`
3. Notice markdown file `text.md`
4. Go back
5. Navigate to `./Folder with spaces`
6. Notice the absence markdown file `text.md`
7. Reload page
8. Notice markdown file `text.md`

This could likely be because when navigating, `Folder with spaces` becomes `Folder%20with%20spaces` (as seen in the breadcumb element), but after a reload it changes back to the correct (url unescaped) form

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by babbitt** [comment]
Hey there @Tc-001. I've resolved this issue with #1144. If you can give that a thumbs up hopefully the maintainers will see and merge.

In the meantime, I'm currently hosting my own fork with some bugfixes (including this one) and features I've worked on @ [joebabbitt.com/prosa](https://joebabbitt.com/prosa). Since I want to avoid standing up my own gatekeeper instance and am keeping everything client-side, I've enabled login via github PAR token. ([You'll need to create a token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) with the repo and user scopes to login).

**Comment by babbitt** [comment]
I've confirmed that merging #1144 fixed this at https://prose.io//#Tc-001/Prose-bug-repro. :tada:
