### ISSUE TITLE
"Error While Loading Data from Github"

### ISSUE THREAD

**Issue by Jackuzzzi** [prose/prose#1134]
Hi all,

When I try to publish changes to Github through Prose, I'm getting the following error: 

![image](https://user-images.githubusercontent.com/120749529/218502897-d761d59b-9ca0-437d-bc71-fb7cd887271f.png)

I've tried clearing prose and Github cookies to no avail, and I'm not too sure where to go from here. Have people encountered this issue before, and how did you resolve?

Thank you for your time!

**Comment by Jackuzzzi** [comment]
It's also not an issue of having the same title as another post on the same Github site

**Comment by babbitt** [comment]
Happy to look into this issue for you but need a bit more info to try and recreate the issue. Is the repo you're working on public? If so, what is it so I can make a fork and check out if I have the same issues.

**Comment by chocmake** [comment]
fwiw some users of our wiki have experienced this error when they haven't first authorized their Github account with Prose.io (the bottom-right green button), since the UI doesn't communicate this is necessary during editing.

**Comment by babbitt** [comment]
Haven't heard anything on this so closing this issue as stale. @Jackuzzzi if the error isn't what chocmake mentioned feel free to reopen.
@chocmake. Noting 643 and will hopefully whittle my back to that issue and have time to figure out a fix. Thanks for the heads up!

**Comment by chocmake** [comment]
Hmm, a user from our community encountered this error and they had authorized Prose with their Github account.

![Screenshot - 1](https://github.com/prose/prose/assets/34178938/277ca9c4-3c42-4ae0-ab3e-71349af54d25)
![Screenshot - 2](https://github.com/prose/prose/assets/34178938/b8b2a87a-fc14-4d0b-babe-325764270770)

They were trying to edit [this](https://mgsvmoddingwiki.github.io/Commands/) page of our wiki (using the top-right colored pencil icon).

[This](https://github.com/mgsvmoddingwiki/mgsvmoddingwiki.github.io/blob/master/_config.yml) is our `_config.yml` (it doesn't have any Prose specific config, just a variable that toggles visibility of the Prose buttons on the site). Our wiki is loosely based on the git-wiki template.

This user only has Contributor status, while some other users who have Collaborator status have successfully been able to use Prose for editing. However I wouldn't think this would make any difference since all edits are submitted as PRs but could this actually affect this?
