### ISSUE TITLE
Edit Astro.build MD or MDX files with Prose interface

### ISSUE THREAD

**Issue by stanislav-kukucka** [prose/prose#1153]
I have tested editing with "Prose" some MD files on the Astro project. It would be fine to be able to edit and modify MD files. Astro MD or MDX files have a specific header (i pasted a sample hereunder). These header values do no load into "Prose" editor. Creating a new copy of a sample MD or MDX file (within the Prose interface) containing header data would be fine too. Astro is getting on the rise and I see "Prose" would be the best option to maintain MD and MDX content easily for non-technical users.

```
---
layout:
title:
description:
author:
date:
---
```

**Comment by babbitt** [comment]
Hi there, 
I'm not really sure what you're looking for. Prose is an editor built for Markdown files. There's no reason astro files shouldn't open just fine in Prose. If you want to define custom frontmatter you can do so via a [config file](https://github.com/prose/prose/wiki/Prose-Configuration). 
Unless I'm missing something here Prose should load these files just fine, maybe you just didn't click on the metadata viewer on the sidebar? 

Marking this as closed. Please provide a repo with examples if your issue is not resolved.
