### ISSUE TITLE
[BUG] publish button gone

### ISSUE THREAD

**Issue by zmike** [prose/prose#1155]
**Describe the bug**
There used to be a button in the top right of the editor to publish a post. The button is no longer there, and posts cannot be published.

**To Reproduce**
1. Create a new pages post
2. Try to publish using the editor
3. ???

**Expected behavior**
I expected to still be able to publish posts through the editor.

**Desktop or Mobile Device (please complete the following information):**
 - OS: linux/desktop
 - Browser all chrome-based browsers
 - Version various versions tested

**Additional context**
On already-published posts, the button is present for unpublishing.

**Bonus points**
Were there any error messages in the browser developer console?
No

**Comment by babbitt** [comment]
Howdy. The publish button has been removed intentionally by PR #1151. There's more detail there as to why this change was made but the TL:DR is:

- The use of `publish` is redundant in jekyll. **All pages are published by default**, The UI has been updated to assume this paradigm. Keeping the unpublish functionality is more in line with how Jekyll is designed.
- adding `publish: true` to every file made with Prose is enforcing jekyll semantics on every user where not every user is using Jekyll.

If your specific use case requires the need for `publish: true` to appear on all files (**again, this not required for having a page go live in Jekyll**), I'd recommend creating a [config file](https://github.com/prose/prose/wiki/Prose-Configuration) with element `publish` and a default value of `true`.

If there's something I'm missing or a use case I haven't covered I'm happy to revisit.

**Comment by zmike** [comment]
Huh okay, thanks for adding context

**Comment by babbitt** [comment]
I wish there was a better way to alert users of the change so there isn't moments of "wait where did this go" (part of why the backwards compatible functionality is still in place for older style pages) but Github doesn't have a great mechanism for updates besides PRs. If I have some time I might formalize my changes into a release every once and a while but since Prose uses CD releases are also kind of arbitrary. If you have ideas I'm happy to hear them!
