### ISSUE TITLE
Switch default content from value to placeholder

### ISSUE THREAD

**Issue by bcomnes** [prose/prose#554]
When editing a post while on an iPhone 4 (and presumably other phones?), its seemingly impossible to select text in a way that can be edited.  

The best way to see this is to create a new post, and delete the placeholder text.  The only way I was able to figure out how was to accomplish this was to hold down the delete button until it was all gone.  Maybe I missed something though.

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by bcomnes** [comment]
Still a problem.  OP has details.
