### ISSUE TITLE
Make meta data input-forms modular to the user providing views in a html file alongside.

### ISSUE THREAD

**Issue by mklarmann** [prose/prose#625]
prose.io could be used as a general purpose database management tool, that is input centric, revision controlled and web-accessible on multiple platforms.

**Comment by fulldecent** [comment]
Recommending to close issue as out of scope

**Comment by fkostadinov** [comment]
Actually, I think this idea is not so bad. I have myself written a simple database management system based on GitHub, Prose, Jekyll, Heroku and a few other tools. It has the following capabilities:

1. User can manipulate data through input forms
2. Only authorized and authenticated users can view or modify the data (relying on GitHub organizations and teams)
3. User can search data with a text search capability

I had to tweak Prose a little, but my solution is still rather ugly. If someone more knowledgeable about the topic would take this idea further on, it would probably not be too hard to include user input forms to Prose instead of only the text editor.

You can find a blog entry with a description of my solution here: http://fabian-kostadinov.github.io/2015/02/04/how-i-created-a-simple-dbms-using-github-jekyll-prose-and-heroku/

I'll happily provide source code for everyone interested.

**Comment by dereklieu** [comment]
I would be open to an enhancement that makes it easier to edit json files, similar to the now-available csv editing (#911). Going beyond that in the way laid out by this ticket is, I think, not the goal of Prose, although I think the DBMS in the attached post is a cool use of the technology.
