### ISSUE TITLE
Title isn't saved when moving a draft to a post

### ISSUE THREAD

**Issue by ttunguz** [prose/prose#641]
I create a title in a draft post and save it. It works. Then I click the link draft to post button and the title is lost. I can see this in the metadata.

draft form
```
---
layout: post
published: false
title: Spending a week on a tablet
---
```

on clicking draft to post
```
---
layout: post
published: false
title: ""
---
```

Here's my config.yml

```
prose:
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

**Comment by dereklieu** [comment]
The issue here is that the title is being inserted [as a placeholder](https://github.com/prose/prose/blob/master/app/views/file.js#L484) due to prose thinking that it's a brand new file.

Same thing happens when you go from a post and create a draft from it in the settings sidebar dialog.

Fix is to check for `&& !isClone()` in addition to the quoted line above.

Will write a fix and tests.
