### ISSUE TITLE
Is there another step to get prose to read a config file?

### ISSUE THREAD

**Issue by bechatman** [prose/prose#647]
I loaded prose without any config information, but I can't seem to make it take the new config I pushed to the repo. I tried it in Jekyll config and separately, but it doesn't take it. I figured out that I had to use spaces instead of tabs, but even that change didn't do anything.

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!
