### ISSUE TITLE
Metadata editing not enabled by default

### ISSUE THREAD

**Issue by nslater** [prose/prose#658]
When I create a new Markdown document, the metadata button on the right is not enabled by default. Nor is the "Published" button, which operates on the metadata.

If I edit an existing document with a pre-existing front matter, these UI elements are made available.

But I'd like them to be made available by default with new documents.

I had a look at the configuration options, and I think there might be a way to get this working for files that live under a directory. But I am trying to do this for files that live in the top level directory.

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by dereklieu** [comment]
Main issue here is closed. Tracking the published button/metadata editor issue in  #869
