### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by alexsalas** [prose/prose#682]
The web site is blank

```SyntaxError: missing } after function body prose.min.js:16```

Under:
```text
Name: Firefox
Version: 31.0a1
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0
```

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by alexsalas** [comment]
Dont worry @fulldecent .

I have a big pull request, maybe tonight I'll send the changes.
To use Prose as Chrome App, Mozilla WebMaker, Mozilla Add-ons, and Desktop App.
