### ISSUE TITLE
Uncaught TypeError: Cannot read property 'files' of undefined 

### ISSUE THREAD

**Issue by ldodds** [prose/prose#694]
I'm having problem using prose.io on a repo. Previously it was working fine, but sometime over the last few days the project has stopped loading, the "Loading Project" icon stays and nothing happens.

The JS log has two errors in it:

`Uncaught TypeError: Cannot read property 'files' of undefined` once from line 19 and once from line 23 in `prose.min.js`

Does anyone know what might cause this? We've not changed the configuration of the project.

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by ldodds** [comment]
I'm not longer employed by the company who had the original issue and so no longer have access to the repo causing the problem. On that basis I'm closing the issue.
