### ISSUE TITLE
Scroll up and down key not working in Firefox/Chromium on Linux

### ISSUE THREAD

**Issue by orschiro** [prose/prose#723]
Hi there,

Can someone confirm that the scroll up/down keys are not fully working on Linux?

When pressing `Shift+PgDn` I expect the editor to scroll down and select text.

Instead it stucks and does not scroll down.

Let me know if I can provide you with more information!

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by orschiro** [comment]
@fulldecent

Thank you for bringing this back up onto the agenda!

This bug is still persisting. Steps to reproduce:

1. I tested the `Shift+PgDn` scroll with [this](http://prose.io/#orschiro/orschiro.github.io/edit/master/_posts/2014-03-03-Mendeley-Desktop-one-of-the-best-PDF-annotation-tools-on-Linux.md) file in my repository. 
2. In both browsers, Firefox and Chromium, this keyboard shortcut is selecting text as opposed to scrolling the text.

**Comment by dereklieu** [comment]
On Ubuntu 14.04 and confirmed that `PgUp`, `PgDn` would not do anything sometimes although I didn't dive into it using Firefox. 

After deploying #943, those buttons now work the same as they do on OSX Chrome. `PgUp` doesn't go all the way up because of the sticky nav, leaving 2-3 lines obscured, but that behavior is the same on both systems and browsers.

Chalking this up to serving a really old version of CodeMirror until now, but @orschiro please let me know if this persists.

**Comment by dereklieu** [comment]
I should also add that `home` and `end` go to the top and bottom of the current paragraph, respectively, which is weird to me but consistent at least across the browsers/operating systems I tried it on.

**Comment by orschiro** [comment]
@dereklieu,

Thank you so much! 

I can happily confirm that the issue is fixed. :+1: 

Warmly,

~Robert
