### ISSUE TITLE
New Maintainer(s)

### ISSUE THREAD

**Issue by parkr** [prose/prose#743]
Prose is looking for (a) new maintainer(s)! If you're passionate about this project and have some great JavaScript chops, we'd love to hear from you.

@dalejefferson [has volunteered](https://twitter.com/DaleJefferson/status/502162417443696640). 

Anyone else up for the challenge?

/cc @tristen

**Comment by crawfordcomeaux** [comment]
Any thoughts on setting Prose up as an [Assembly.com side project](http://sideprojects.assembly.com/)?

**Comment by pksunkara** [comment]
I am willing to maintain this if this gets put on [Assembly.com](sideprojects.assembly.com)

**Comment by awwstn** [comment]
Member of the Assembly core team here – I'm happy to answer questions about what it means to put something like this on Assembly. (austin@assembly.com)

**Comment by mikemorris** [comment]
Not interested in monetizing. Handing over the rights to monetize Prose to an organization with that intent is definitely not going to happen, sorry @crawfordcomeaux @pksunkara @awwstn.

**Comment by crawfordcomeaux** [comment]
Assembly doesn't require projects to monetize, though you do want to make sure that's explicitly stated so that people don't join the project with the idea that it will be monetized in the future. I think if you maintain control of the project on Assembly as the sort of BDFL, then you can easily make sure that'll continue being the case.

**Comment by erlend-sh** [comment]
So @awwstn what could being on Assembly (Sideprojects) do for a project like Prose? After some quick reading I fail to see what it is Assembly actually offers developers that simply being on GitHub doesn't do already, at least when money & equity is not involved.

**Comment by Koxzi95** [comment]
I'm all for helping even if it just means testing pull requests and sorting out issues. 

It's sad to see it so dead currently.

**Comment by phillipadsmith** [comment]
@parkr Ping. Lots of issues & PRs that need attention. Is there a path to a resolution so that this project can get moving again?

**Comment by tristen** [comment]
If you're you submit a pull request that looks reasonable I'm happy to add
you as a collaborator.

**Comment by phillipadsmith** [comment]
> If you're you submit a pull request that looks reasonable I'm happy to add
you as a collaborator.

@tristen Fair enough. 

Can one assume that the PRs that are there already are being reviewed? I think that's what is the general concern, i.e., that someone is reviewing issues and PR as they come in.

**Comment by mikemorris** [comment]
I've been commenting occasionally to provide general guidance/feedback but haven't really done any technical review or testing of most outstanding pull requests @phillipadsmith.

**Comment by daveas** [comment]
@parkr & others - has anyone considered transferring the ownership of Prose to Jekyllrb? Is there another CMS-like solution that has more steam than prose?

**Comment by ChrisChinchilla** [comment]
@parkr 

I got shown prose by someone here in Berlin and loved the idea, it fits into a lot of the work I am currently undertaking.

I'd be happy to have a chat about maintaining and see if I have the skills to do so.

**Comment by dereklieu** [comment]
@ChrisChinchilla that's awesome. I'm sending you a note over email using the address in your handle. Would love to help you get up to speed anyway I can.

**Comment by phillipadsmith** [comment]
@dereklieu @ChrisChinchilla I'm also interested in lending a hand.

**Comment by ChrisChinchilla** [comment]
Great @philipadsmith we're trying to arrange a catch up time, will keep you updated

**Comment by TimoSolo** [comment]
I'm keen to help! I've used prose for a while for some static sites and wanted to fix the image upload. Do you guys have a roadmap? Where can I get involved?

**Comment by phillipadsmith** [comment]
Hey there @TimoSolo, great to hear. @ChrisChinchilla and I have both had a quick chat with @dereklieu and are slowly digging our way through the open tickets and codebase. I'd encourage you to do the same and then dig in.

For example, there are some proposed improvements to the image upload / image selection in a recent pull request that you may want to review. 

There are also several open issues relating to images/image uploading, which you may want to get up to speed on: https://github.com/prose/prose/milestones/Priority

The "roadmap" as described by @dereklieu is to get the project to "stable" -- i.e., stably working for most users -- and then to review next steps from there.

Perhaps you can take a look at the above and then propose some ways you'd like to jump in?

**Comment by grobmeier** [comment]
Hi

I am an open source guy (working for years at the Apache software foundation mostly) with some js skills. Part of my day job is to build websites with Jekyll. In genera I am huge fan of static page generation (even wrote a book on Apache Forrest back then). 

Now I would love to see this project grow again so I can safely use it. I certainly miss some js skills (not worked too much with node) but I am not too bad otherwise. Also do I know a little on community building and open source in general.
I would love to have a google hangout or something with some interested ppl to see if we share common grounds and visions. Forming a team around prose would be amazing and certainly catch some interest. I have some non technical customers maintaining Jekyll using a weird combo of cron job and Dropbox. They would love a maintained prose!!

What about chatting end of August?
Thanks!

**Comment by phillipadsmith** [comment]
@grobmeier Glad to see your interest. @ChrisChinchilla and I have been discussing the same. 

In the meantime, it would be helpful to get your take on these [priority issues](https://github.com/prose/prose/milestones/Priority) and a sense of where you'd like to jump in.

**Comment by RaghuAllTheTime** [comment]
I want to be a contributor.
I will help add customizability, and if i can, in an autosuggest feature in Prose.

**Comment by erlend-sh** [comment]
@phillipadsmith & co, once things have settled a bit, it'd be great if you could drop by [talk.jekyllrb.com] and kind of summarise what's been happening lately, who's involved and how you're moving forward.

Since Prose is intended to serve the less technical Jekyll users, it makes sense to post updates to Talk once in a while, where you'll likely reach more of these users than you through just GitHub.

**Comment by phillipadsmith** [comment]
> @phillipadsmith & co, once things have settled a bit, it'd be great if you could drop by talk.jekyllrb.com and kind of summarise what's been happening lately, who's involved and how you're moving forward.

Good idea. 

I'm [over there regularly](https://talk.jekyllrb.com/users/phillipadsmith/activity). 

I'll make a point of keeping an eye out for threads asking about editors.

**Comment by nexocentric** [comment]
I have been using Jekyll for a little bit now. I have used Prose too. I'd like to talk about lending a hand. Most definitely don't want to see the project die off.

**Comment by dereklieu** [comment]
Hey @nexocentric glad to hear it! Going to get in touch via the email listed on your GH account.

**Comment by nexocentric** [comment]
Thanks a lot for the message @dereklieu . I look forward to hearing from you.

**Comment by dereklieu** [comment]
@nexocentric getting a bounce back from the email in your sig. Can you email me at the email in mine?

**Comment by M3kH** [comment]
Hi everybody,
I love Prose.
And I'm a JS lover, since that I'm a Metalsmith user. :-)

I took a quick look at the https://github.com/prose/prose/milestones/Priority
and from what I notice seems that prose needs some 'services' in his infrastructure.

Just mentioning some:
 - Oauth
 - Upload but not commit #501 
 - Anonymous PR's #643

So I skip those issues because IMO they don't belong to this repo.
I then I also notice that issues like #825 are responsibilities that belong to an eventually prose.io repository.

I think the separation of the prose and prose.io, can help to get more contributors to the repos.
While also would help to focus on be bundled/self-hosted tool/CMS; that would bring more users to Prose and improving the quality of the codebase.

To conclude is a shame not mention some Dev-Goodness, like:
 - Switch from es5 -> es6
 - Backbone -> Marionette ( or whatever )
 - Ability to add plugins.

I would prefer done a PR to introduce my self.
But I thought this feedbacks can be more useful before actually put some code.

What you think? I'm in a wrong vision?
If you think is valuable for prose, do you want me to create the issues?

Cheers!

**Comment by mikemorris** [comment]
Ah, yea, breaking `prose/prose.io` out into a separate repo might be a good idea @M3kH, and would help clean up the separation of a library with tagged releases and a site running a release of the library.

**Comment by M3kH** [comment]
Thanks @mikemorris then you can consider my first contribution at #900 :+1:
Tell me if I can help with it! Or anything else.

**Comment by catherine-jones** [comment]
Are you still looking for maintainers?

**Comment by dereklieu** [comment]
@catherine-jones Yes, help is very much appreciated to close out bug issues and write unit tests, as well as work on any enhancements ticketed out or otherwise. Let me know if you've got any questions about the code base, I'd be happy to chat.

**Comment by frontcraft** [comment]
What is status of the project? Is it currently maintained by anybody? When looking to commits history it seems that no one is interested in further development. We should revive Prose - it is awesome and should be more popular because it may change the way we look on a Static Site Generators! I wrote about this on my blog post called "You might not need Wordpress" https://blog.mvp-space.com/you-might-no-need-wordpress-c06ef4c4f98b 

So, are there any plans for the future?

**Comment by erlend-sh** [comment]
Considering Prose is not under any clear leadership and the codebase is not actively maintained, wouldn't it be better to redirect developers to an actively supported project with company backing behind it?

@biilmann's https://github.com/netlify/netlify-cms has a lot of potential!

**Comment by frontcraft** [comment]
I tested both. Prose has more potential in my opinion. It is easier to set up and does not require third party platforms. Also it's ui is good. Anyway, all of them should be developed. It is better to do not mix the topics. 

We need a team, leader/coordinator and more detailed contribution instructions

**Comment by mehdisadeghi** [comment]
Adapt [C4.1](https://rfc.zeromq.org/spec:22/C4/) and let prose organically grow.

**Comment by arkokoley** [comment]
Are you still looking for maintainers?

**Comment by dereklieu** [comment]
@arkokoley yes, if you're interested, email me at the address in my profile.

**Comment by 32bpwr3** [comment]
I am not a programmer, but I would help where I can. I have experience with bug tracking, project management, and qa testing. Email me: editor@shepherdhistory.org.

**Comment by patcon** [comment]
I'm interested in doing issue triage sometime. Would someone be able to put me on a team with at minimum read access (which will allow me to label and open/close issues)

Push or admin access would be appreciated as well, if you're comfortable with that :)

cc: @tristen

**Comment by dereklieu** [comment]
@patcon just added you to a read access team!

**Comment by Oxyenyos** [comment]
@dereklieu 
Are you still looking for maintainers?
I've decent javascript skills and need to fix some of your existing issues before it becomes useable for me, as I need it to work on gitlab.

**Comment by dy** [comment]
I'm also planning to use it for a project and already used for a couple. If you wish I can opt in for some maintenance not to keep it abandoned.

**Comment by babbitt** [comment]
@dereklieu Not sure if you're still looking as this project has been dead for quite a while now but I've been putting in some work to try and get it back on the ground running. (#1142 #1143 #1144 #1145)
 It seems like a lot of the core dependencies are on their way out themselves but definitely happy to help bootstrap prose back into remission and see if there's any appetite for more work then.

**Comment by tristen** [comment]
👋 thanks for your interest in the project @babbitt! you're right: there are no active maintainers but I've added you to the contributors list which grants write access.

**Comment by babbitt** [comment]
@tristen Awesome. Do you know if you could also grant me access to the transifex org so I could test, merge, and maintain the translation efforts I've been working on (#1145) ?

**Comment by tristen** [comment]
@babbitt sure can 👍 what is your username on Transifex?
