### ISSUE TITLE
prose.io has no SSL - security / privacy issue

### ISSUE THREAD

**Issue by sammcj** [prose/prose#883]
http://prose.io version of the website available (https://prose.io) - this is a serious security / privacy concern especially given that it authenticates with people's Github (which yes, I know partially uses Github's SSL for outh but that doesn't help other than for authentication).

I only just noticed this today and it worries me quite a bit.
- Resolution: Add a SSL cert to prose.io, then redirect http access to the site to https
- Cost: SSL certs are about $10, happy to pay for this if money is the issue
- Complexity: Easy

**Comment by dereklieu** [comment]
Would love to get this done, in addition to #825.

**Comment by mikemorris** [comment]
Yes, this should definitely happen.

**Comment by northox** [comment]
+1

**Comment by dereklieu** [comment]
Since prose.io is hosted on github pages, it's a bit more complicated than just buying a cert. We're in discussions on the best way to support HTTPS, but in the meantime, if you need HTTPS on the hosted version of prose you can use [https://prose.github.io/prose/](https://prose.github.io/prose/)

**Comment by jgillich** [comment]
@dereklieu I'm using Cloudflare SSL together with Pages and it works great. Are there any concerns about it?

**Comment by gsf** [comment]
With CloudFlare SSL, and even with https://prose.github.io/prose/, there is still a segment between the CDN and GitHub's servers where data is passed back and forth via plain HTTP (github/issues#156).

**Comment by jgillich** [comment]
@gsf You can set SSL to full in the Cloudflare CP and it will then use the HTTPS site. Of course GitHub doesn't have the correct cert, so you can't use strict.

**Comment by gsf** [comment]
@jgillich Yes but even the HTTPS for GitHub pages (https://*.github.io) is SSL terminated at their CDN, passing the data in the clear over that last segment. See [this comment](https://github.com/isaacs/github/issues/156#issuecomment-75738734) on that thread I referenced.

**Comment by dereklieu** [comment]
Ah wow @gsf I missed that comment in that thread, although it would seem to be a very important one.

**Comment by ehausen** [comment]
+1

**Comment by jmatsushita** [comment]
How about https://pages.gitlab.io/ ?

**Comment by rnkn** [comment]
In the interim, can you please disable the prose.io CNAME and put a 302 redirect to https://prose.github.io/prose?

If anyone is confused, it's probably easy to explain to them the benefits of SSL over a nice URL.

**Comment by janpio** [comment]
@rnkn As I understood it github.io has the same "problem" as putting Cloudflare in front of prose.io, so this would be "misleading" as well - so no win in getting rid of the accustomed domain.

My two cents: I think using Cloudflare with the unsecured connection between GH and CF should be fine and still much better than the current state. (I think just having the domain behind CF will greatly improve cookie security and similar things.)

**Comment by blairmacintyre** [comment]
Have you considered using https://netlify.com to host the site?  I moved a bunch of my github repos to using it instead of github pages.  It's free (unless you want their premium features), auto publishes, and allows you to use SSL with your own domain via LetsEncrypt (e.g., https://argonjs.io and associated sites are hosted there, every time we check something in it gets published automatically ... it's great!)

**Comment by tornewuff** [comment]
@janpio github.io does not have that problem any more - see https://github.com/blog/2186-https-for-github-pages and specifically "You have been able to request Pages sites over HTTPS for some time, but we refrained from officially supporting it because the traffic from our CDN to our servers wasn't encrypted until now."

This happened since the earlier comments in this thread in 2015, so it was accurate at the time.

So, yes, it seems like the right thing to do now is what @rnkn suggested and just have prose.io redirect back to https://prose.github.io/prose

**Comment by dereklieu** [comment]
https://prose.io
