### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by joshcomley** [prose/prose#908]
As Prose.io is built especially with Jekyll in mind, should it support code highlighting in the preview like so:

    {% highlight ruby %}
    void SomeLovelyCode() {}
    {% endhighlight %}

Currently it doesn't work, but I'm not sure if this is a bug or a missing feature.

**Comment by alexkleinubing** [comment]
+1

And add a button "code"

**Comment by dereklieu** [comment]
Prose uses CodeMirror to edit and display code, line numbers, and highlighting. As such, we're somewhat limited by the [number of languages CodeMirror has syntax highlighting for](http://codemirror.net/mode/). 

Currently you can see [which ones we include by default](https://github.com/prose/prose/blob/master/app/boot.js#L4-L12). Prose then deduces which one to apply based on the file extension.

@joshcomley based on these constraints, I think a feature like the one you're suggesting would be a tough one to implement, since as far as I know it's either one language or nothing. However, I'd be totally happy to include another language in our list to highlight if there's a good argument towards including it for everyone.
